### ISSUE TITLE
evil-want-Y-yank-to-eol is not equivalent to y$

### ISSUE THREAD

**Issue by rieje** [noctuid/evil-guide#6]
`evil-want-Y-yank-to-eol` is not equivalent to y$. The former yanks from the beginning of the line to the end of the line whereas the latter yanks from the current cursor to the end of the line. How can I replicate this behavior on emacs?

**Comment by noctuid** [comment]
I commented on the reddit thread as well. The issue is probably that you are setting it with setq after evil loads. The evil documentation mentions that the `evil-want` variables should be set before loading evil (this applies only if you are using `setq`; put `(setq evil-want-Y-yank-to-eol t)` before requiring evil or in the `:init` section if you use use-package). This is because some of these variables use `:initialize` and `:set` (see [here](https://emacs.stackexchange.com/questions/102/advantages-of-setting-variables-with-setq-instead-of-custom-el) for further explanation).
